name: Migrate database

on:
  push:
     branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Migrate database
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      
      - name: Migrate database
        if: success()
        env:
          NODE_ENV: production
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bun run db:migrate